site_name: ALCF User Guide
nav:
  - Home: README.md
  - Data Management:
    - ALCF Community Data Co-Op: data-management/acdc/acdc-overview.md
    - Sharing on Eagle Using Globus: data-management/acdc/eagle-data-sharing.md
    - Data Transfer:
      - SFTP and SCP: data-management/data-transfer/sftp-scp.md
      - Using Globus: data-management/data-transfer/using-globus.md
    - File System & Storage:
      - Data Storage: data-management/filesystem-and-storage/data-storage.md
      - Theta File Systems: data-management/filesystem-and-storage/theta-file-systems.md
      - HPSS: data-management/filesystem-and-storage/hpss.md
      - Theta Disk Quota: data-management/filesystem-and-storage/theta-disk-quota.md
      - Polaris Disk Quota: data-management/filesystem-and-storage/polaris-disk-quota.md
      - Cooley Disk Quota: data-management/filesystem-and-storage/cooley-disk-quota.md
  - Polaris:
    - Getting Started: polaris/getting-started.md
    - Known Issues: polaris/known-issues.md
    - Hardware Overview:
      - Polaris Machine Overview: polaris/hardware-overview/machine-overview.md
      - Slingshot Network: polaris/hardware-overview/slingshot-network.md
    - Compiling and Linking:
      - Compiling and Linking Overview: polaris/compiling-and-linking/compiling-and-linking-overview.md
      - Programming Models: polaris/compiling-and-linking/polaris-programming-models.md
      - Example Program and Makefile: polaris/compiling-and-linking/polaris-example-program-makefile.md
      - CCE Compilers: polaris/compiling-and-linking/cce-compilers-polaris.md
      - GNU Compilers: polaris/compiling-and-linking/gnu-compilers-polaris.md
      - NVIDIA Compilers: polaris/compiling-and-linking/nvidia-compiler-polaris.md
      - LLVM Compilers: polaris/compiling-and-linking/llvm-compilers-polaris.md
      - Continuous Integration: polaris/compiling-and-linking/continuous-integration-polaris.md
    - Build Tools:
        - CMake: polaris/build-tools/cmake-polaris.md
    - Queueing and Running Jobs on Polaris:
      - Job Scheduling and Execution: polaris/queueing-and-running-jobs/job-and-queue-scheduling.md
      - Example Job Scripts: polaris/queueing-and-running-jobs/example-job-scripts.md
      - Cobalt to PBS option Comparison: polaris/queueing-and-running-jobs/pbs-qsub-options-table.md
      - The Grounkulator (Job Status Display): polaris/queueing-and-running-jobs/gronkulator.md
      - PBS Admin Quick Start Guide: polaris/queueing-and-running-jobs/pbs-admin-quick-start-guide.md
    - Data Management:
        - ALCF Community Data Co-Op: polaris/data-management/acdc/acdc-overview.md
        - Sharing on Eagle: polaris/data-management/acdc/eagle-data-sharing.md
        - Data Transfer:
          - SFTP and SCP: polaris/data-management/data-transfer/sftp-scp.md
          - Using Globus: polaris/data-management/data-transfer/using-globus.md
        - File System & Storage:
          - Polaris Disk Quota: polaris/data-management/filesystem-and-storage/polaris-disk-quota.md
    - Applications and Libraries:
        - Applications:
            - LAMMPS: polaris/applications-and-libraries/applications/lammps.md
        - Libraries:
            - Math Libraries: polaris/applications-and-libraries/libraries/math-libraries.md
            - Cabana: polaris/applications-and-libraries/libraries/cabana-polaris.md
    - Data Science Workflows:
        - Containers: polaris/data-science-workflows/containers/containers.md
        - Balsam: polaris/data-science-workflows/balsam.md
    - Programming Models: 
        - OpenMP: polaris/programming-models/openmp-polaris.md
        - SYCL: polaris/programming-models/sycl-polaris.md
        - Kokkos: polaris/programming-models/kokkos-polaris.md
    - Debugging Tools:
        - Debugging Tools Overview: polaris/debugging-tools/debugging-overview.md
        - CUDA-GDB: polaris/debugging-tools/CUDA-GDB.md
    - Performance Tools:
        - Performance Tools Overview: polaris/performance-tools/performance-overview.md
        - NVIDIA-Nsight: polaris/performance-tools/NVIDIA-Nsight.md
  - Theta:
    - Hardware Overview:
      - Theta Machine Overview: theta/hardware-overview/machine-overview.md
      - Theta Memory Modes: theta/hardware-overview/theta-memory-modes.md
      - Aries Network: theta/hardware-overview/aries-network.md
    - Compiling And Linking:
      - Compiling and Linking Overview: theta/compiling-and-linking/compiling-and-linking-overview.md
      - Library and Compiler Tracking: theta/compiling-and-linking/theta-library-compiler-tracking-overview.md
      - Example Program and Makefile: theta/compiling-and-linking/theta-example-program-makefile.md
      - Clang Compiler: theta/compiling-and-linking/clang-compiler-theta.md
      - Continuous Integration: theta/compiling-and-linking/continuous-integration-theta.md
    - Queueing and Running Jobs on Theta:
      - The Grounkulator (Job Status Display): theta/queueing-and-running-jobs/gronkulator.md
      - Job and Queue Scheduling: theta/queueing-and-running-jobs/job-and-queue-scheduling.md
      - Machine Reservations: theta/queueing-and-running-jobs/machine-reservations.md
      - Affinity on Theta: theta/queueing-and-running-jobs/affinity-theta.md
    - Data Management:
        - ALCF Community Data Co-Op: theta/data-management/acdc/acdc-overview.md
        - Sharing on Eagle Using Globus: theta/data-management/acdc/eagle-data-sharing.md
        - Data Transfer:
          - SFTP and SCP: theta/data-management/data-transfer/sftp-scp.md
          - Using Globus: theta/data-management/data-transfer/using-globus.md
        - File System & Storage:
          - Theta File Systems: theta/data-management/filesystem-and-storage/theta-file-systems.md
          - HPSS: theta/data-management/filesystem-and-storage/hpss.md
          - Theta Disk Quota: theta/data-management/filesystem-and-storage/theta-disk-quota.md
    - Applications and Libraries:
        - Applications:
          - ELPA: theta/applications-and-libraries/applications/elpa.md
          - Grommacs: theta/applications-and-libraries/applications/grommacs.md
          - LAMMPS: theta/applications-and-libraries/applications/lammps.md
          - NAMD: theta/applications-and-libraries/applications/namd.md
          - NwChem: theta/applications-and-libraries/applications/nwchem.md
          - QMCPack: theta/applications-and-libraries/applications/qmcpack.md
          - QBox: theta/applications-and-libraries/applications/qbox.md
          - Quantum Espresso: theta/applications-and-libraries/applications/quantum-espresso.md
          - Quantum Package: theta/applications-and-libraries/applications/quantum-package.md
          - VASP: theta/applications-and-libraries/applications/vasp.md
          - WEST: theta/applications-and-libraries/applications/west.md
    - Data Science Workflows:
          - Balsam: theta/data-science-workflows/balsam.md
    - Programming Models: 
          - OpenMP: theta/programming-models/openmp-theta.md
    - Debugging Tools: theta/debugging-tools/debugging-overview.md
    - Performance Tools: theta/performance-tools/performance-overview.md 
  - ThetaGPU:
    - Hardware Overview:
      - ThetaGPU Machine Overview: theta-gpu/hardware-overview/theta-gpu-machine-overview.md
    - Compiling And Linking:
      - Compiling and Linking Overview: theta-gpu/compiling-and-linking/compiling-and-linking-overview.md
      - Continuous Integration: theta-gpu/compiling-and-linking/continuous-integration-theta.md
    - Queueing and Running Jobs on ThetaGPU:
      - Job and Queue Scheduling: theta/queueing-and-running-jobs/job-and-queue-scheduling.md
      - Machine Reservations: theta/queueing-and-running-jobs/machine-reservations.md
    - Data Science:
      - Data Science Software Availability: theta-gpu/data-science/data-science-software-availability.md
      - Building Python Packages: theta-gpu/data-science/building-python-packages.md
      - GPU Monitoring: theta-gpu/data-science-workflows/gpu-monitoring.md
      - GPU Node Queue and Policy: theta-gpu/data-science/gpu-node-queue-and-policy.md
      - Jupyter Hub: theta-gpu/data-science/jupyter-hub.md
      - Python/C++ Code Interoperability: theta-gpu/data-science/pythonc-code-interoperability.md
      - Singularity on ThetaGPU: theta-gpu/data-science/singularity.md
      - Deep Learning Frameworks:
        - Distributed Training on ThetaGPU Using Data Parallelism: heta-gpu/data-science/dl-frameworks/distributed-training-using-data-parallelism.md
        - Running PyTorch with Conda: theta-gpu/data-science/dl-frameworks/running-pytorch-conda.md
        - Running Tensorflow with Conda: theta-gpu/data-science/dl-frameworks/running-tensorflow-conda.md
        - Tensorboard Instructions: theta-gpu/data-science/dl-frameworks/tensorboard-instructions.md
    - Programming Models: 
      - Kokkos: theta-gpu/programming-models/kokkos.md
      - OpenMP: theta-gpu/programming-models/openmp.md
      - Raja: theta-gpu/programming-models/raja.md
    - Performance Tools: 
      - Darshan: theta-gpu/programming-models/darshan.md
      - NVIDIA Nsight: theta-gpu/performance-tools/nvidia-nsight.md
  - Cooley:
    - Hardware Overview:
      - Cooley Machine Overview: cooley/cooley-overview.md
    - Compiling And Linking:
      - Compiling and Linking Overview: cooley/compiling-and-linking/compiling-and-linking.md
    - Queueing and Running Jobs:
      - Job and Queue Scheduling: cooley/job-submission/job-and-queue-scheduling.md
    - Data Science:
      - Data Science Software Availability: theta-gpu/data-science/data-science-software-availability.md
    - Software and Libraries: 
      - Jupyter Notebooks: cooley/software-and-libraries/jupyter-notebooks.md
      - Machine Learning Tools: cooley/software-and-libraries/machine-learning-tools.md
      - ParaView: cooley/software-and-libraries/paraview.md
      - ParaView Tutorial: cooley/software-and-libraries/paraview-tutorial.md
      - Singularity on Cooley: cooley/software-and-libraries/singularity-cooley.md
      - Visit on Cooley: cooley/software-and-libraries/visit-on-cooley.md
    - Performance Tools: 
      - Darshan: cooley/programming-models/darshan.md
      - Remote Visualization Using VNC: cooley/performance-tools/remote-visualization-using-vnc.md
  - Edith (Edge Dev Testbed):
      - Getting Started: polaris/queueing-and-running-jobs/edtb.md

theme:
  name: 'material'
  custom_dir: overrides
  language: 'en'
  palette:
    scheme: alcf
  font:
    text: proxima-nova
  features:
    - tabs
    - instant
    - search.highlight
    - search.suggest
  logo: 'images/Argonne_wireframe_white_transparent.png'
  favicon: 'images/alcf_favicon.ico'

extra_css:
  - stylesheets/alcf-extra.css

extra_javascript:
  - javascripts/alcf-extra.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

repo_name: 'argonne-lcf/alcf-userguide'
repo_url: 'https://github.com/argonne-lcf/alcf-userguide'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcf/alcf-userguide'

plugins:
  - search



